In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [8]:
#importing the training data
train = pd.read_csv('train.csv')

In [9]:
train.head(10)

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   
5      0       0       0       0       0       0       0       0       0   
6      7       0       0       0       0       0       0       0       0   
7      3       0       0       0       0       0       0       0       0   
8      5       0       0       0       0       0       0       0       0   
9      3       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   
5       0  ...         0         0         0         0         0         0   
6       0  ...         0         0         0         0         0         0   
7       0  ...         0         0         0         0         0         0   
8       0  ...         0         0         0         0         0         0   
9       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  
5         0         0         0         0  
6         0         0         0         0  
7         0         0         0         0  
8         0         0         0         0  
9         0         0         0         0  

[10 rows x 785 columns]

In [10]:
#Extracting and converting the features and target to nd-arrays
X_train = train.iloc[:,1:].values
y_train = train.iloc[:,0].values.reshape(-1,1)

In [11]:
y_train

array([[1],
       [0],
       [1],
       ...,
       [7],
       [6],
       [9]], dtype=int64)

In [12]:
y_train.shape

(42000, 1)

In [13]:
# Encoding categorical data
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_y = LabelEncoder()
y_train[:,0] = labelencoder_y.fit_transform(y_train[:,0])
onehotencoder = OneHotEncoder(categorical_features = [0])
y_train = onehotencoder.fit_transform(y_train).toarray()

c:\users\dare\envs\controls\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [14]:
y_train.shape

(42000, 10)

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
y_train = sc.fit_transform(y_train)

In [16]:
y_train.shape

(42000, 10)

In [17]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [18]:
#initializing the ANN
classifier = Sequential()

#adding the input and hidden layer
classifier.add(Dense(output_dim=397, init='uniform', activation='relu', input_dim=784))

In [19]:
#adding the second hidden layer
classifier.add(Dense(units = 397, activation = 'relu', init = 'uniform'))

In [20]:
#adding the output layer
classifier.add(Dense(output_dim=10, init='uniform', activation='softmax'))

In [21]:
#compiling the ANN
classifier.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [22]:
y_train.shape

(42000, 10)

In [ ]:
#fitting the classifier
classifier.fit(X_train,y_train,batch_size=28,epochs=25)

Epoch 1/25
42000/42000 [==============================] - 59s 1ms/step - loss: -44.3818 - acc: 0.9134
Epoch 2/25
42000/42000 [==============================] - 52s 1ms/step - loss: -46.4777 - acc: 0.9557
Epoch 3/25
42000/42000 [==============================] - 51s 1ms/step - loss: -46.8322 - acc: 0.9650: 0s - loss: -46.8381
Epoch 4/25
42000/42000 [==============================] - 64s 2ms/step - loss: -46.9984 - acc: 0.9695
Epoch 5/25
42000/42000 [==============================] - 62s 1ms/step - loss: -47.1384 - acc: 0.9736
Epoch 6/25
42000/42000 [==============================] - 63s 2ms/step - loss: -47.1684 - acc: 0.9736: 10s - loss: - ET
Epoch 7/25
42000/42000 [==============================] - 57s 1ms/step - loss: -47.2191 - acc: 0.9758
Epoch 8/25
42000/42000 [==============================] - 53s 1ms/step - loss: -47.2110 - acc: 0.9760
Epoch 9/25
42000/42000 [==============================] - 57s 1ms/step - loss: -47.3081 - acc: 0.9782
Epoch 10/25
42000/42000 [==================

In [31]:
test = pd.read_csv('test.csv')
X_test = test.iloc[:,0:].values

In [25]:
X_test = sc.fit_transform(X_test)

c:\users\dare\envs\controls\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
c:\users\dare\envs\controls\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [32]:
y_pred = classifier.predict(X_test)

In [42]:
y_pred[100,:]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

In [44]:
decoded = y_pred.dot(onehotencoder.active_features_).astype(int)

c:\users\dare\envs\controls\lib\site-packages\sklearn\utils\deprecation.py:77: DeprecationWarning: Function active_features_ is deprecated; The ``active_features_`` attribute was deprecated in version 0.20 and will be removed 0.22.
  warnings.warn(msg, category=DeprecationWarning)


In [45]:
decoded

array([2, 0, 9, ..., 3, 9, 2])

In [87]:
id = np.arange(1,28001)

In [88]:
combined = np.vstack((id, decoded)).T

In [89]:
submission = pd.DataFrame(data=combined)

In [90]:
submission.rename(columns={0:'ImageId',1:'Label'}, inplace = True)


In [91]:
submission.to_csv("submission.csv",index=False)